name: Deploy to Azure VM

on:
  push:
    branches:
      - main  # Change to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t meerebusflask:latest .
          docker tag meerebusflask:latest ${{ secrets.DOCKER_USERNAME }}/meerebusflask:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/meerebusflask:latest

      - name: SSH to Azure VM and Deploy
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "docker-compose.yml"  # If you're using Docker Compose; adjust as needed
          target: "/path/on/your/vm"

      - name: SSH to Azure VM and Run Docker Commands
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/meerebusflask:latest
            docker stop $(docker ps -q --filter ancestor=${{ secrets.DOCKER_USERNAME }}/meerebusflask)
            docker rm $(docker ps -aq --filter ancestor=${{ secrets.DOCKER_USERNAME }}/meerebusflask)
            docker run -d -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/meerebusflask:latest
