name: Deploy to Azure VM

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          # Build from the root directory (Site), specifying the Dockerfile location
          docker build -t meerebusflask:latest -f backend/Dockerfile .
          docker tag meerebusflask:latest ${{ secrets.DOCKER_USERNAME }}/meerebusflask:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/meerebusflask:latest

      - name: SSH to Azure VM and Deploy
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            ssh -vvv my30cmthroat@48.218.168.55
            # Pull the latest image
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/meerebusflask:latest
            
            # List Docker images for debugging
            sudo docker images
            
            # Check if a container is running
            CONTAINER_ID=$(sudo docker ps -q --filter ancestor=${{ secrets.DOCKER_USERNAME }}/meerebusflask)
            if [ -n "$CONTAINER_ID" ]; then
              # If a container is running, stop and remove it
              echo "Stopping and removing existing container..."
              sudo docker stop $CONTAINER_ID
              sudo docker rm $CONTAINER_ID
            else
              echo "No existing container found."
            fi
            
            # Run the new container
            echo "Running the new container..."
            sudo docker run -d -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/meerebusflask:latest
