name: CI/CD for Vue Frontend and Selenium Tests

on:
  push:
    branches:
      - main
      - test-ci

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install frontend dependencies
        run: |
          cd SPM-MeeRebus  # Navigate to your Vue project
          npm install

      - name: Build frontend
        run: |
          cd SPM-MeeRebus
          npm run build

      - name: Deploy to Vercel (Staging)
        run: |
          cd SPM-MeeRebus
          npm install -g vercel
          vercel --token ${{ secrets.VERCEL_TOKEN }} --prod  # Deploy to staging
        id: deploy_staging

  get_preview_url:
    needs: deploy_to_staging
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Vercel Preview URL
        uses: zentered/vercel-preview-url@v1.1.9
        id: vercel_preview_url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
          branch: test-ci
      - name: Output Preview URL
        run: echo "Preview URL: ${{ steps.vercel_preview_url.outputs.preview_url }}"
        id: output_url

  selenium_tests:
    needs: get_preview_url
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Selenium dependencies
        run: |
          cd selenium-testing
          pip install selenium pytest

      - name: Run Selenium tests
        run: |
          cd selenium-testing
          echo "Testing against: ${{ steps.output_url.outputs.preview_url }}"
          python -m pytest --url "${{ steps.output_url.outputs.preview_url }}"

  deploy_to_production:
    needs: selenium_tests
    if: success()  # Only deploy to production if tests pass
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Vercel (Production)
        run: |
          cd SPM-MeeRebus
          npm install -g vercel
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }}  # Deploy to production