name: CI/CD for Vue Frontend and Selenium Tests

on:
  push:
    branches:
      - main
      - test-ci

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install frontend dependencies
        run: |
          cd SPM-MeeRebus  # Navigate to your Vue project
          npm install

      - name: Build frontend
        run: |
          cd SPM-MeeRebus
          npm run build

      - name: Deploy to Vercel (Staging)
        run: |
          cd SPM-MeeRebus
          npm install -g vercel
          vercel --token ${{ secrets.VERCEL_TOKEN }}  # Deploy to staging
        id: deploy_staging

      - name: Get the Vercel Preview URL
        uses: zentered/vercel-preview-url@v1.1.9
        if: github.event_name != 'pull_request'
        id: vercel_preview_url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          GITHUB_REF: "main"
          GITHUB_REPOSITORY: "your-repo/your-project"
        with:
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Wait for Vercel Deployment Readiness
        uses: UnlyEd/github-action-await-vercel@v1
        id: await-vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          deployment-url: ${{ steps.vercel_preview_url.outputs.preview_url }}
          timeout: 420
          poll-interval: 15

  selenium_tests:
    needs: deploy_to_staging
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Selenium dependencies
        run: |
          cd selenium-testing
          pip install selenium pytest

      - name: Get Vercel URL from previous step
        run: |
          echo "Using Vercel Preview URL: ${{ steps.vercel_preview_url.outputs.preview_url }}"

      - name: Run Selenium tests
        run: |
          cd selenium-testing
          pytest selenium-test.py --url "${{ steps.vercel_preview_url.outputs.preview_url }}"

  deploy_to_production:
    needs: selenium_tests
    if: success()  # Only deploy to production if tests pass
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Vercel (Production)
        run: |
          cd SPM-MeeRebus
          npm install -g vercel
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }}  # Deploy to production