name: CI/CD for Vue Frontend

on:
  push:
    branches:
      - main
      - test-ci

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install frontend dependencies
        run: |
          cd SPM-MeeRebus  # Navigate to your Vue project
          npm install

      - name: Build frontend
        run: |
          cd SPM-MeeRebus
          npm run build

      - name: Deploy to Vercel (Staging)
        run: |
          cd SPM-MeeRebus
          npm install -g vercel
          vercel --token ${{ secrets.VERCEL_TOKEN }}  # Deploy to staging
        id: deploy_staging

  selenium_tests:
    needs: deploy_to_staging
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Selenium dependencies
        run: |
          cd selenium-testing 
          pip install selenium pytest

      - name: Get the Vercel URL
        run: |
          cd SPM-MeeRebus/SPM-MeeRebus 
          export FRONTEND_URL=$(vercel url --token ${{ secrets.VERCEL_TOKEN }})
          echo "Deployed URL: $FRONTEND_URL"

      - name: Run Selenium tests
        run: |
          cd selenium-testing  
          export FRONTEND_URL=$(vercel url --token ${{ secrets.VERCEL_TOKEN }})
          echo "Testing against: $FRONTEND_URL"
          python -m pytest --url "$FRONTEND_URL"

  deploy_to_production:
    needs: selenium_tests
    if: success()  # Only deploy to production if tests pass
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Vercel (Production)
        run: |
          cd SPM-MeeRebus
          npm install -g vercel
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }}  # Deploy to production
